<!DOCTYPE html>
<html lang="fr">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Voyages de rêves</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?=ROOT_CSS?>bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="<?=ROOT_CSS?>blog-home.css" rel="stylesheet">
    <link href="<?=ROOT_CSS?>blog-post.css" rel="stylesheet">
    <link href="<?=ROOT_CSS?>style.css" rel="stylesheet">   
    <link rel="stylesheet" href="<?=ROOT_JS?>raty-2.7.0/lib/jquery.raty.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="<?=ROOT_CSS?>timepicker.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- <script src="//code.jquery.com/jquery-1.10.2.js"></script>-->

    </head>
    <body>

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand glyphicon glyphicon-home" href="<?= ROOT ?>"></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="<?=ROOT?>categories"><span class="glyphicon glyphicon-th-list"></span> Catégories</a>
                        </li>
                        <li>
                            <a href="<?=ROOT?>auteurs"><span class="glyphicon glyphicon-pencil"></span> Auteurs</a>
                        </li>
                        <li class="messages">
                            <a href="<?=ROOT?>ecrivezNous"><span class="glyphicon glyphicon-envelope"></span> Ecrivez-nous</a>
                        </li>                       

                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> Admin <span class="caret"></span></a>
                          <ul class="dropdown-menu" role="menu">

                            <?php if (isConnected()): ?>   
                             <li>
                             <a href="<?=ROOT?>dashboard"> <span class="glyphicon glyphicon-dashboard"></span> Dashboard</a>
                         </li>                                                   
                     <?php endif ?>
                     <?php if (isConnected()==true): ?>
                     <li>
                        <a href="<?=ROOT?>login"><span class="glyphicon glyphicon-log-out"></span> Se déconnecter</a>
                    </li>
                <?php else: ?>
                <li>
                    <a href="<?=ROOT?>login"><span class="glyphicon glyphicon-log-in"></span> Se connecter</a>
                </li>
            <?php endif ?>
        </ul>
    </ul>
</li>
</ul>

</div>
<!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>
