  <?php 
  //On place la liste des categories ici pour éviter un bug lors de l'include de la sidebar dans articleView.phtml. Comme on change de page, on recréé la connexion et la requête.
  $sql="SELECT *, count(article.titre) as nbCat, categories.id as cat FROM categories
LEFT JOIN article ON categories.id=article.id_categorie
group by categories.id
order by `nom` asc";
  $requete = $connexion->prepare($sql);
  $success = $requete->execute();
  $sidebarCategories=$requete->fetchAll(PDO::FETCH_ASSOC);
  // var_dump($sidebarCategories);

  //Récupération des commentaires
$sql="SELECT *, article.titre FROM `commentaire`
INNER JOIN article ON commentaire.id_article = article.id
order by `date_commentaire` desc
LIMIT 1";
$requete = $connexion->prepare($sql);
$success = $requete->execute();
$lastCommentaires=$requete->fetchAll(PDO::FETCH_ASSOC);
// var_dump($lastCommentaires);
  ?>
  <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">

    <!-- Blog Search Well -->
    <form method="GET" action="index.php" autocomplete="off">
      <div class="well">
        <h4><span class="glyphicon glyphicon-search"></span> Rechercher sur le Blog</h4>
        <div class="input-group">
          <input id="inputSearch" name="word" type="text" class="form-control">
          <input name="page" value="recherche" type="hidden">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </form>
        </span>
      </div>
      <!-- /.input-group -->
      <ul id="resultatRecherche">
      </ul>
    </div>

    <!-- Blog Categories Well -->
    <div class="well">
      <h4><span class="glyphicon glyphicon-th-list"></span> Categories</h4>
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-unstyled">
            <?php foreach ($sidebarCategories as $key => $value): ?>
              <li role="presentation"><a href="<?=ROOT?>listeCategories-<?php echo $value['cat']; ?>"><?php echo $value['nom']; ?></a> <span class="badge"><?php echo $value['nbCat'] ?></span></li>             
          <?php endforeach ?>
        </ul>
      </div>
    </div>
    <!-- /.row -->
  </div>

  <!-- Side Widget Well -->
  <div class="well">
    <h4><span class="glyphicon glyphicon-comment"></span> Dernier commentaire</h4>
   <?php foreach ($lastCommentaires as $key => $value): ?>
                <div class="media">
                    <a class="pull-left" href="#">

                    </a>
                    <div class="media-body">
                        <h4 class="media-heading"><?php echo $value['user']; ?><br>
                            <small><?php echo "a posté le ".date('d-m-Y \à\ H:i:s', strtotime($value['date_commentaire'])); ?></small>
                        </h4><div>dans l'article <a href="<?=ROOT?>article-<?php echo $value['id_article']; ?>"><?php echo $value['titre'] ?></a></div>
                        <div class="ratyCommentaire" data-number="<?php echo $value['note']; ?>"></div> 
                        <?php echo $value['contenu']; ?>
                    </div>
                </div>
                <?php endforeach ?> 
  </div>

</div>

</div>
<!-- /.row -->

<hr>