
<?php include"globals/header.phtml" ?>
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

     <div class="jumbotron">
      <h1>Ajouter un auteur</h1>
      <p class="lead">Vous pouvez ajouter simplement un auteur<br>Tous les champs doivent être remplis.</p>
      <!--         <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p> -->
<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> <a href="<?=ROOT?>dashboard">Revenir au Dashboard</a></button>      
    </div>
    <div class="col-lg-12">
      <form method="POST" action="<?=ROOT?>ajoutAuteur" enctype="multipart/form-data">
        <div class="form-group">
          <label for="nom">Nom</label>
          <input type="text" class="form-control" name="nom" id="nom" placeholder="Nom de l'auteur">
        </div>
        <?php 
          if (array_key_exists("nom", $erreurs)) {
              echo '<p class="alert alert-danger">'.$erreurs['nom'].'</p>';
          } ?>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea type="text" class="form-control" cols="30" rows="3" name="description" id="description" placeholder="Description de l'auteur"></textarea>
        </div>
        <?php 
          if (array_key_exists("description", $erreurs)) {
              echo '<p class="alert alert-danger">'.$erreurs['description'].'</p>';
          } ?>        
        <p></p>
        <div class="form-group">
    <label for="image">Choisir une image</label>
         
    <input type="file" name="image" id="image"><div><?php echo $_FILES["image"]['name'] ?></div>
    <p class="help-block">Format : JPG ou PNG.<br>Dimension : Inférieure à 1000x1000px et au format carré.<br>Taille : inférieure à 2mo.</p>
  </div>
  <?php 
          if (array_key_exists("image", $erreurs)) {
              echo '<p class="alert alert-danger">'.$erreurs['image'].'</p>';
          } ?>  
        <button type="submit" class="btn btn-primary"><span class=" glyphicon glyphicon-plus-sign"></span> Ajouter</button>
        <p></p>
        <?php 
        if (isset($successAddAuteur) && $successAddAuteur==true) {
            echo '<p class="alert alert-success alert-block">Votre auteur a bien été ajouté.</p>';
        }
        ?>        
      </form>          
    </div>

  </div>
  <?php include"globals/sidebar.phtml" ?>
  <?php include"globals/footer.phtml" ?>