
<?php include"globals/header.phtml" ?>
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">
           <div class="jumbotron">
      <h1>Messages reçus des utilisateurs.</h1>
      <p class="lead">Consulter, supprimer, les messages reçus.
      <!--         <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p> -->
    </div>
          <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span> <a href="<?=ROOT?>dashboard">Revenir au Dashboard</a></button>       
<p></p>
<table class="table table-striped table-bordered table-hover">
    <tbody><tr>
        <th>Prénom</th>
        <th>Nom</th>
        <th>Message</th>
        <th>Reçu le</th>
        <th>Action</th>
    </tr>
    </tbody><tbody>
    <?php foreach ($allMessages as $key => $value): ?>
           <tr> <td><?php echo $value['prenom'] ?></td><td><?php echo $value['nom'] ?></td><td><?php echo getLittleDescription($value['message']) ?></td><td><?php echo date('d-m-Y \à\ H:i:s', strtotime($value['date_message'])); ?></td><td><button type="button" class="btn btn-xs btn-info glyphicon glyphicon-eye-open" data-toggle="modal" data-target="#<?php echo $value['id'] ?>">
</button>&nbsp;
                  
                  <a class="btn btn-xs btn-danger glyphicon glyphicon-trash" href="#"></a>
              </td></tr> 

<div class="modal" id="<?php echo $value['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $value['prenom'] ?> <?php echo $value['nom'] ?> a écrit : </h4>
      </div>
      <div class="modal-body">
       <?php echo $value['message'] ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>
<?php endforeach ?> 
   </tbody>
    </table>



        <!-- Pager -->
        <nav>
            <ul class="pagination pagination-sm">           
                <?php 
                $nbPage=ceil($nbreMessages[0]/4);
                $i=1;
                for ($i; $i<=$nbPage; $i++): ?>
                    <?php if($paginationPage == $i) : ?>
                        <li class="active">
                    <?php else : ?>
                        <li>
                    <?php endif; ?>

                    <!-- <li class="<?php //echo ($paginationPage == $i ? 'active' : '') ?>"> -->
                        <a href="<?=ROOT?>pageMessageDashboard<?php echo $i;?>"><?php echo$i;?></a>
                    </li>
            <?php endfor ?>     
        </ul>
<!-- Button trigger modal -->


<!-- Modal -->

    </nav>
<!--     <ul class="pager">
        <li class="previous">
            <a href="#">&larr; Articles précédents</a>
        </li>
        <li class="next">
            <a href="#">Articles suivants &rarr;</a>
        </li>
    </ul> -->
</div>
<?php include"globals/sidebar.phtml" ?>
<?php include"globals/footer.phtml" ?>