
<?php include"globals/header.phtml" ?>
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

     <div class="jumbotron">
      <h1>Ecrivez-nous !</h1>
      <p class="lead">Une suggestion, une demande, un avis sur le blog. <br>Ca se passe ici !</p>
      <!--         <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p> -->
    </div>
    <div class="col-lg-12">
      <form method="POST" action="<?=ROOT?>ecrivezNous" enctype="multipart/form-data">
        <div class="form-group">
          <label for="prenom">Prénom</label>
          <input type="text" class="form-control" name="prenom" id="prenom" placeholder="Entrer votre prénom">
        </div>
        <?php 
          if (array_key_exists("prenom", $erreurs)) {
              echo '<p class="alert alert-danger">'.$erreurs['prenom'].'</p>';
          } ?>        
        <div class="form-group">
          <label for="nom">Nom</label>
          <input type="text" class="form-control" name="nom" id="nom" placeholder="Entrer votre nom">
        </div>
        <?php 
          if (array_key_exists("nom", $erreurs)) {
              echo '<p class="alert alert-danger">'.$erreurs['nom'].'</p>';
          } ?>
        <div class="form-group">
          <label for="message">Votre message</label>
          <textarea type="text" class="form-control" cols="30" rows="3" name="message" id="message" placeholder="Ecrivez votre message ici."></textarea>
        </div>
        <?php 
          if (array_key_exists("message", $erreurs)) {
              echo '<p class="alert alert-danger">'.$erreurs['message'].'</p>';
          } ?>        
        <p></p>
        <button type="submit" class="btn btn-primary"><span class=" glyphicon glyphicon-send"></span> Envoyer</button>
        <p></p>
        <?php 
        if (isset($successAddMessage) && $successAddMessage==true) {
            echo '<p class="alert alert-success alert-block">Votre message a bien été envoyé.</p>';
        }
        ?>        
      </form>          
    </div>

  </div>
  <?php include"globals/sidebar.phtml" ?>
  <?php include"globals/footer.phtml" ?>